"""add column to task type

Revision ID: f259ccad6d8d
Revises: f87f0ae8e2a0
Create Date: 2024-04-18 15:07:48.250465

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f259ccad6d8d"
down_revision = "f87f0ae8e2a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.Enum("LEISURE", "WORK", "STUDY", "REST", "OTHER", name="tasktype"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
